### ISSUE TITLE
Tcl in .modulerc

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#81]
The contents of `.modulerc` is:
```tcl
#%Module1.0
if {[info exists ::env(VSC_DEFAULT_CLUSTER_MODULE)]} {
    module-version cluster/$::env(VSC_DEFAULT_CLUSTER_MODULE) default
} else {
    puts stderr "The default cluster module cannot be determined. Please set \$VSC_DEFAULT_CLUSTER_MODULE."
    exit 1
}
```
If you use this with Lmod in the case that `$VSC_DEFAULT_CLUSTER_MODULE` is unset, you get:
```
The default cluster module cannot be determined. Please set $VSC_DEFAULT_CLUSTER_MODULE.
/apps/gent/SL6/sandybridge/software/Lua/5.1.4-8/bin/lua: ...6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/utils.lua:841: [string "modA={"]:1: unexpected symbol near '<eof>'
stack traceback:
	[C]: in function 'assert'
	...6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/utils.lua:841: in function 'versionFile'
	...od/6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MT.lua:168: in function 'buildAvailT'
	...od/6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MT.lua:128: in function 'buildAvailT'
	...od/6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MT.lua:492: in function '_build_locationTbl'
	...od/6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MT.lua:1182: in function 'locationTbl'
	....0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MAlias.lua:155: in function 'resolve'
	...6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MName.lua:282: in function 'lazyEval'
	...6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/MName.lua:313: in function 'sn'
	....16-05fb4e1-hpc-ugent/lmod/lmod/libexec/cmdfuncs.lua:394: in function 'cmd'
	...Lmod/6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/lmod:650: in function 'main'
	...Lmod/6.0.16-05fb4e1-hpc-ugent/lmod/lmod/libexec/lmod:695: in main chunk
	[C]: ?
```

Can we do anything to avoid this stack traceback? Lmod does not expect to find an `exit 1` in the `.modulerc`?

**Comment by rtmclay** [comment]
Thanks for the bug report!  I have pushed a new version (6.0.18) which doesn't return the stack trace:

% ml av
The default cluster module cannot be determined. Please set $VSC_DEFAULT_CLUSTER_MODULE.
Lmod has detected the following error:  Unable to parse: /home/user/.modulerc  Aborting!

**Comment by wpoely86** [comment]
I still get the same stacktrace. The trace comes from `utils.lua:841` and the changes you made are in `MAlias.lua` ?

**Comment by rtmclay** [comment]
O.K. I fixed the other one.  Please pull HEAD and try it again.

**Comment by wpoely86** [comment]
Almost there:
```
/apps/gent/SL6/sandybridge/software/Lua/5.1.4-8/bin/lua: ...6.0.18-be2e2ef-hpc-ugent/lmod/lmod/libexec/utils.lua:844: variable 'fn' is not declared
```

**Comment by rtmclay** [comment]
O.K.  please pull HEAD and try it again.
Thanks,

**Comment by wpoely86** [comment]
It works. Thanks @rtmclay!

**Comment by rtmclay** [comment]
What command did you do get the above problem?

**Comment by wpoely86** [comment]
We have a directory `cluster` with the above `.modulerc`. If you unset the variable `$VSC_DEFAULT_CLUSTER_MODULE` and do `ml load cluster`, you get the error from above.

**Comment by rtmclay** [comment]
Thanks,  Closing issue
