### ISSUE TITLE
exit statement in module files

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#90]
From the man page of modules:
```
 exit [N]

    This is not a modules specific command but another overloaded Tcl command and is similar to the break or continue commands. However, this command will cause the immediate cessation of this module and any additional ones on the command line. This module and the subsequent modules will not be listed as loaded. No environment commands will be performed in the current module.

    The integer value N after the exit command will be used as an command exit value; however, some shells (bash being one of them) do not carry this value through an eval though. For bash and those Bourne shells (/bin/sh) being emulated by the bash will have return a non-zero value as a result of test 0 = 1 being appended to the evaluate string. 
```

Testcase. 
```bash
$ cat mymodule
#%Module
puts stderr "Big bad error message"
exit 1

$ ml mymodule
Big bad error message

$ ml
Currently Loaded Modules:
  1) mymodule

```

I believe the `mymodule` should not be loaded?

**Comment by rtmclay** [comment]
This has been fixed

**Comment by hpourreza** [comment]
I have this version "Modules based on Lua: Version 6.3 (6.3-1-gdc8b375) 2016-04-19 16:02" but still shows module as installed even though I have exit 1 in my module file. Which file do I need to replace or should I get 6.4?

**Comment by rtmclay** [comment]
You will have to get the latest version from github (version 6.4.3)

**Comment by hpourreza** [comment]
Thanks. I downloaded 6.4.3 and now it does not show the module as loaded but I am getting:
 "Lmod has detected the following error:  Unable to load module: xx" 
/path/to/xx : Non-zero status returned 

Is there anyway not to show this error message to the user and simply exit from the module (similar to the break command in TCL module file)?

**Comment by rtmclay** [comment]
I try when I can to reproduce Tmod behavior.  In this case Lmod is
reproducing Tmod behavior.  At least it is with my test module

$ cat error/1.0#%Module
puts stderr "Big bad error message"exit 1


Tmod reports an error and Lmod is as well.  This is correct behavior.  Are
you seeing something different?

R.

On Fri, Jun 17, 2016 at 1:46 PM, hpourreza <notifications@github.com> wrote:

> Thanks. I downloaded 6.4.3 and now it does not show the module as loaded
> but I am getting:
> "Lmod has detected the following error: Unable to load module: xx"
> /path/to/xx : Non-zero status returned
>
> Is there anyway not to show this error message to the user and simply exit
> from the module (similar to the break command in TCL module file)?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/TACC/Lmod/issues/90#issuecomment-226850386>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AB8maKy8zhnDfQVI0TWk6aNsckzGuRK5ks5qMuuIgaJpZM4HQcxH>
> .
>



-- 
Robert McLay, Ph.D.
TACC
Manager, HPC Software Tools
(512) 232-8104

**Comment by hpourreza** [comment]
#%Module
puts stderr "Big bad error message \n"
break or exit 0 or exit 1
When I load the above Tmod module (using module 3.2.10), I only see the message (no extra error message from TCL) and it does not appear in the loaded module list. 
Lmod does not parse the Tmod break command and having exit 0 still shows the module as loaded (could be ok or not) and having exit 1 prints extra error messages with a caption in red (LmodError's output).

**Comment by wpoely86** [comment]
@hpourreza with the new lmoderror part of the msg hook, you can alter the error output in any way you like.

**Comment by rtmclay** [comment]
I have started to look at this and it is clear to me that supporting break would require a major change in the way that Lmod works.  I am going to close this issue and open another one because the issue with break really has nothing to do with exit.
